# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7711109cee37d44b56fda0c2b3bab4afa9b1105bf85ada8131b8ef833b0f21c71e5056bbc9e2be69f2134679e450a824243430e405d6d0bdd6c7cdf3626c0fb4

test:
  secret_key_base: 27736e81c54e770b59b5cfb35bc5a013f38bf3dbde2a7be2296f14afe79ada66a75b049e4e84a419fe82084fe6b11d8107d225caf0ba915c9790ea5dada55902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
